[package]
name = "solana_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.79"
axum = "0.6.18"
discord = { git = "https://github.com/SpaceManiac/discord-rs" }
reqwest = { version = "0.12", features = ["json"], default-features = false }
thiserror = "1"
regex = "1.10.4"
serde = { version = "1", features = ["derive", "std", "alloc"], default-features = false }
serde_json = "1.0.115"
serenity = "0.12.1"
stringr = "0.1.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
url = "2"
