[package]
name = "solana_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
reqwest = { version = "0.12", features = ["json"], default-features = false }
thiserror = "1"
serde = { version = "1", features = ["derive", "std", "alloc"], default-features = false }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
url = "2"
